### ISSUE TITLE
error on trigger()

### ISSUE THREAD

**Issue by ered15** [br0sk/yii2-pusher#4]
When i run `Yii::$app->pusher->trigger( 'my-channel', 'my_event', 'hello world' );` im getting this error:

`PHP Recoverable Error 'yii\base\ErrorException' with message 'Argument 2 passed to yii\base\Component::trigger() must be an instance of yii\base\Event, string given, called in C:\wamp\www\yii2\greengo\controllers\SiteController.php on line 3564 and defined'`

any idea whats the issue?

**Comment by rudissaar** [comment]
Have you tried using `push` instead of `trigger`?
```
Yii::$app->pusher->push('my-channel', 'my_event', 'hello world'); 
```

**Comment by ered15** [comment]
@rudissaar I just tried,  no error but also no notification, I created a custom function and its working fine:

`public function send_request($title,$message,$channel='my-channel',$event='my-event'){
        $options = array(
            'cluster' => 'us2',
            'useTLS' => true
        );
        $pusher = new \Pusher(
            'XXX',
            'XXX',
            'XXX',
            $options
        );                
        $data['title'] = $title;
        $data['message'] = $message;
        $pusher->trigger($channel, $event, $data);
    }`

**Comment by rudissaar** [comment]
If you are using Yii2 then you should at least use `br0sk/yii2-pusher` version >= 1.0.0 because version 0.1.0 uses method named `trigger` instead of `push` because `trigger` keyword is already used by Yii2's `Event` object, it was not like this for Yii1, also to keep in mind that this plugin deals only with emitting signals, not with receiving them.

I hope this explains what the issue might be, @ered15 are you okay if we close this issue?
